### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by couchand** [carloskiki/icondata#26]
This project looks very interesting and useful.  I'm confused about the licensing situation here.  The readme mentions:

> Licenses of the icons provided through these libraries were extracted with best intent, but must only be taken as a hint. Please check the individual icon repositories for up-to-date license information.

It seems like understanding and complying with the terms of the source package licenses would be a necessary first step ahead of repackaging them for distribution?  There are important terms that this project might not be in compliance with. For instance, at least the MIT-licensed projects expect their copyright notice to be maintained.

**Comment by Carlosted** [comment]
This was added to the readme because the licenses are autogenerated by a build script, but I checked them and they are correct. 

Isn't a mention enough? What would you recommend we do more? I'm open to removing this sentence from the readme if it's the problem.
