### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by paul-hansen** [carloskiki/icondata#38]
Just a heads up, been down for a few days: https://carlosted.github.io/icondata It was really handy.

Thanks for this crate, lmk there's anything we can help with.

**Comment by carloskiki** [comment]
Should be fixed as of now. Can you give it a try?

Thank you!

**Comment by KOEGlike** [comment]
For me, it doesn't work right now.

Thanks for the real good crate, it's a lifesaver in wasm and leptos.

**Comment by paul-hansen** [comment]
New links are working for me too. Thanks!
