### ISSUE TITLE
Get icon from name

### ISSUE THREAD

**Issue by glennpierce** [carloskiki/icondata#41]
Sorry I looked around but can't find an answer.

If I have a string like. RiSaveDeviceLine (I want to store this in a db)

Is it possible to load the icon from the name

Ie

get icondata::RiSaveDeviceLine

so I can do

<Icon icon=icondata::RiSaveDeviceLine />

**Comment by carloskiki** [comment]
Yeah, this is a good one.

Previously, we (the crate) had an enum with all icons that was serializable, and therefore we could do that. We don't anymore, so right now you could theoretically serialize and compress the whole `IconData` struct (since there is `serde` support), but it is overkill.

If you only need a small subset of icons, you could solve this by having an enum like:
```rust
#[derive(Serialize, Deserialize)]
enum Icons {
    RiSaveDeviceLine,
    ...
}
```
This would map the icon name to the `icondata::RiSaveDeviceLine`.

If its for all icons in this crate, then there is no other way than to compress them. Otherwise you could also open a PR against this repo and add the feature :)

**Comment by glennpierce** [comment]
> Yeah, this is a good one.
> 
> Previously, we (the crate) had an enum with all icons that was serializable, and therefore we could do that. We don't anymore, so right now you could theoretically serialize and compress the whole `IconData` struct (since there is `serde` support), but it is overkill.
> 
> If you only need a small subset of icons, you could solve this by having an enum like:
> 
> ```rust
> #[derive(Serialize, Deserialize)]
> enum Icons {
>     RiSaveDeviceLine,
>     ...
> }
> ```
> 
> This would map the icon name to the `icondata::RiSaveDeviceLine`.
> 
> If its for all icons in this crate, then there is no other way than to compress them. Otherwise you could also open a PR against this repo and add the feature :)

The only way I can think of of implementing the feature is to maintain a runtime hashmap and a macro to make it easier when defining icons ? 

ie something like

```
use std::collections::HashMap;
use once_cell::sync::Lazy;

// Define a global, lazily-initialized HashMap to store the icons
static ICON_MAP: Lazy<HashMap<&'static str, &'static icondata_core::IconData>> = Lazy::new(|| {
    let mut map = HashMap::new();
    map
});

// The macro that defines the icon and inserts it into the global HashMap
macro_rules! define_icon {
    ($name:ident, $data:expr) => {
        #[allow(non_upper_case_globals)]
        pub static $name: &icondata_core::IconData = &$data;

        ICON_MAP.get_mut().unwrap().insert(stringify!($name), $name);
    };
}

// Use the macro to define icons
define_icon!(AiAccountBookFilled, icondata_core::IconData {
    style: None,
    x: None,
    y: None,
    width: None,
    height: None,
    view_box: Some("0 0 1024 1024"),
    stroke_linecap: None,
    stroke_linejoin: None,
    stroke_width: None,
    stroke: None,
    fill: None,
    data: r###"<path d="M880 184H712v-64c0-4.4-3.6-8-8-8h-56c-4.4 0-8 3.6-8 8v64H384v-64c0-4.4-3.6-8-8-8h-56c-4.4 0-8 3.6-8 8v64H144c-17.7 0-32 14.3-32 32v664c0 17.7 14.3 32 32 32h736c17.7 0 32-14.3 32-32V216c0-17.7-14.3-32-32-32zM648.3 426.8l-87.7 161.1h45.7c5.5 0 10 4.5 10 10v21.3c0 5.5-4.5 10-10 10h-63.4v29.7h63.4c5.5 0 10 4.5 10 10v21.3c0 5.5-4.5 10-10 10h-63.4V752c0 5.5-4.5 10-10 10h-41.3c-5.5 0-10-4.5-10-10v-51.8h-63.1c-5.5 0-10-4.5-10-10v-21.3c0-5.5 4.5-10 10-10h63.1v-29.7h-63.1c-5.5 0-10-4.5-10-10v-21.3c0-5.5 4.5-10 10-10h45.2l-88-161.1c-2.6-4.8-.9-10.9 4-13.6 1.5-.8 3.1-1.2 4.8-1.2h46c3.8 0 7.2 2.1 8.9 5.5l72.9 144.3 73.2-144.3a10 10 0 0 1 8.9-5.5h45c5.5 0 10 4.5 10 10 .1 1.7-.3 3.3-1.1 4.8z" />"###
});
```
