### ISSUE TITLE
Add PatternFly icons

### ISSUE THREAD

**Issue by phill-85** [carloskiki/icondata#42]
Great project. Any chance you can add the PatternFly icons? 

They're available here: https://github.com/patternfly/patternfly-design/tree/master/resources/patternfly-icon-svgs/patternfly-icons.
More info also here: https://www.patternfly.org/design-foundations/icons/

**Comment by carloskiki** [comment]
The library is not popular enough to be added to `icondata`, but you could very well make your own library with our build tool.
